using Photon.Pun;
using UnityEngine;
using UnityEngine.UI;
using GorillaNetworking;

public class VRRig : MonoBehaviourPun
{
	public VRMap head;
	public VRMap rightHand;
	public VRMap leftHand;
	public VRMapThumb leftThumb;
	public VRMapIndex leftIndex;
	public VRMapMiddle leftMiddle;
	public VRMapThumb rightThumb;
	public VRMapIndex rightIndex;
	public VRMapMiddle rightMiddle;
	public bool isOfflineVRRig;
	public GameObject mainCamera;
	public Transform playerOffsetTransform;
	public int SDKIndex;
	public bool isMyPlayer;
	public AudioSource leftHandPlayer;
	public AudioSource rightHandPlayer;
	public AudioSource tagSound;
	[SerializeField]
	private float ratio;
	public Transform headConstraint;
	public Vector3 headBodyOffset;
	public GameObject headMesh;
	public Vector3 syncPos;
	public Quaternion syncRotation;
	public AudioClip[] clipToPlay;
	public AudioClip[] handTapSound;
	public int currentMatIndex;
	public int setMatIndex;
	public float lerpValueFingers;
	public float lerpValueBody;
	public GameObject backpack;
	public Transform leftHandTransform;
	public Transform rightHandTransform;
	public SkinnedMeshRenderer mainSkin;
	public GameObject spectatorSkin;
	public int handSync;
	public Material[] materialsToChangeTo;
	public float red;
	public float green;
	public float blue;
	public string playerName;
	public Text playerText;
	public bool showName;
	public GameObject[] cosmetics;
	public string concatStringOfCosmeticsAllowed;
	public bool initializedCosmetics;
	public string badge;
	public string face;
	public string hat;
	public string leftHandHold;
	public string rightHandHold;
	public string tryOnRoomBadge;
	public string tryOnRoomFace;
	public string tryOnRoomHat;
	public string tryOnRoomLeftHandHold;
	public string tryOnRoomRightHandHold;
	public bool inTryOnRoom;
	public bool muted;
	public float doNotLerpConstant;
	public string tempString;
	public ParticleSystem lavaParticleSystem;
	public ParticleSystem rockParticleSystem;
	public ParticleSystem iceParticleSystem;
	public string tempItemName;
	public CosmeticsController.CosmeticItem tempItem;
	public string tempItemId;
	public int tempItemCost;
	public int leftHandHoldableStatus;
	public int rightHandHoldableStatus;
	public AudioSource[] musicDrums;
	public ActionableItem[] instrumentSelfOnly;
	public float bonkTime;
	public float bonkCooldown;
	public bool isQuitting;
	public GameObject huntComputer;
}
